@echo off
echo Cleaning up ports 5174-5176...
powershell -ExecutionPolicy Bypass -Command "Get-NetTCPConnection -LocalPort 5174,5175,5176 -State Listen | Where-Object { $_.OwningProcess -ne $PID } | ForEach-Object { taskkill /PID $_.OwningProcess /F }"
echo Starting dev server on port 5173...
npm run dev
